<template>

    <div class="policy">
      <div class="color"></div>
        <appHeader></appHeader>
        <div class="container-fluid">
          <div class="container">
            <div class="row">
            <div class="col-md-12">
              <h1 class="superHeader">Our Privacy Policy</h1>

              <div id="sections">
                <section class="first-section sec1" >

                  <div v-show="!read1">
                    <h2 class="introHeader">We are here to protect you</h2>
                    <button class="btn1" v-show="!read1" @click="read1 = !read1"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                    <!--<button v-show="showMore2" @click="showMore2 = !showMore2">Show Less</button>-->
                  </div>

                  <div v-show="read1">
                    <h2 class="subHeader">We are here to protect you <img src="../assets/images/Vector.png"></h2><br><br>

                    <p>
                      Check retail is committed to protecting your privacy. This Privacy Policy explains how your personal information
                      is collected, used, and disclosed by check retail.<br><br>

                      This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”)
                      alongside our application, check retail. By accessing or using our Service, you signify that you have read,
                      understood, and agree to our collection, storage, use, and disclosure of your personal information as
                      described in this Privacy Policy and our Terms of Service.<br>

                      <button class="btn1 close" v-show="read1" @click="read1 = !read1"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br>
                    </p>
                  </div>
                </section>





                <section class="sec2">

                  <div v-show="!read2">
                    <h2 class="introHeader">Definitions and key terms</h2>
                    <button class="btn1 btn2" v-show="!read2" @click="read2 = !read2"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                    <!--<button v-show="showMore2" @click="showMore2 = !showMore2">Show Less</button>-->
                  </div>

                  <div v-show="read2">
                    <h2 class="subHeader">Definitions and key terms <img src="../assets/images/checklist-1.png"></h2><br><br>

                    <p>
                      To help explain things as clearly as possible in this Privacy Policy, every time any of these
                      terms are referenced, are strictly defined as:<br><br>

                      <table>
                        <tr>
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</p></td>
                        </tr>

                        <tr>
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to paddle technologies, (14, ORANGE GATE, PLAMER STREET, OLUYOLE ESTATE IBADAN, IBADAN, OYO STATE, NIGERIA) that is responsible for your information under this Privacy Policy.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Country: where check retail or the owners/founders of check retail are based, in this case is Nigeria</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Customer: refers to the company, organization or person that signs up to use the check retail Service to manage the relationships with your consumers or service users.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit check retail and use the services.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Personnel: refers to those individuals who are employed by check retail or are under contract to perform a service on behalf of one of the parties.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Service: refers to the service provided by check retail as described in the relative terms (if available) and on this platform.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>Website/APP: check retail."’s" site, which can be accessed via this URL:</p></td>
                        </tr>

                        <tr v-show="showMore1">
                          <td><p><img src="../assets/images/Vector3.png" class="mark-icon"></p></td>
                          <td><p>You: a person or entity that is registered with check retail to use the Services.</p></td>
                        </tr>
                      </table>
                      <button v-show="!showMore1" @click="showMore1 = !showMore1">Read More</button>
                      <button v-show="showMore1" @click="showMore1 = !showMore1">Show Less</button><br>

                      <button class="btn1 btn2 close" v-show="read2" @click="read2 = !read2"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br>
                      <!--hghf<br>uuy<br>-->
                    </p>
                  </div>
                </section>






                <section class="sec3">
                  <div v-show="!read3">
                    <h2 class="introHeader">What Information Do We Collect?</h2>
                    <button class="btn1 btn3" v-show="!read3" @click="read3 = !read3"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read3">
                    <h2 class="subHeader">What Information Do <br>We Collect? <img src="../assets/images/Vector2.png" class="subheade-img"></h2><br>

                    <p>
                      We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.

                      <table class="section3-table">
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Name / Username</p></td>
                        </tr>
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Phone Numbers</p></td>
                        </tr>
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Email Addresses</p></td>
                        </tr>
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Mailing Addresses</p></td>
                        </tr>
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Password</p></td>
                        </tr>
                        <tr>
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Gender</p></td>
                        </tr><br><br>

                      </table>
                        <p v-show="showMore2">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>


                      <table>
                        <tr v-show="showMore2">
                          <td><p><img src="../assets/images/Vector4.png" class="mark-icon"></p></td>
                          <td><p>Photo Gallery (Pictures): Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this app.</p></td>
                        </tr>
                      </table>
                      <button v-show="!showMore2" @click="showMore2 = !showMore2">Read More</button>
                      <button v-show="showMore2" @click="showMore2 = !showMore2">Show Less</button><br>

                      <button class="btn1 btn3 close" v-show="read3" @click="read3 = !read3"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br>
                    </p>
                  </div>
                </section>





                <section class="sec4">
                  <div v-show="!read4">
                    <h2 class="introHeader">How Do We Use The Information we collect?</h2>
                    <button class="btn1 btn4" v-show="!read4" @click="read4 = !read4"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read4">
                    <h2 class="subHeader">How Do We Use The<br> Information We Collect? </h2><br><br>

                    <p>Any of the information we collect from you may be used in one of the following ways:<br>
                      <table>
                        <tr>
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>To personalize your experience (your information helps us to better respond to your individual needs)</p></td>
                        </tr>

                        <tr>
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</p></td>
                        </tr>

                        <tr v-show="showMore3">
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</p></td>
                        </tr>

                        <tr v-show="showMore3">
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>To process transactions</p></td>
                        </tr>

                        <tr v-show="showMore3">
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>Enabling you to participate in promotions, competitions and surveys.</p></td>
                        </tr>

                        <tr v-show="showMore3">
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>Complying with our legal obligations, including verifying your identity where necessary.</p></td>
                        </tr>

                        <tr v-show="showMore3">
                          <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                          <td><p>Detecting fraud.</p>

                            <tr v-show="showMore3">
                              <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                              <td><p>To administer a contest, promotion, survey or other site feature</p></td>
                            </tr>
                            <tr v-show="showMore3">
                              <td><p><img src="../assets/images/Vector5.png" class="mark-icon"></p></td>
                              <td><p>To send periodic emails</p></td>
                            </tr>
                          </td>
                        </tr>
                      </table>
                      <button v-show="!showMore3" @click="showMore3 = !showMore3">Read More</button>
                      <button v-show="showMore3" @click="showMore3 = !showMore3">Show Less</button><br>

                      <button class="btn1 btn4 close" v-show="read4" @click="read4 = !read4"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br>
                    </p>
                  </div>
                </section>






                <section class="sec5">
                  <div v-show="!read5">
                    <h2 class="introHeader">When does check retail use end user information from third parties?</h2>
                    <button class="btn1 " v-show="!read5" @click="read5 = !read5"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read5">
                    <h2 class="subHeader">When does check retail<br> use end user information from third parties? </h2><br>

                    <p>
                      Check retail will collect End User Data necessary to provide the check retail services to our customers.<br><br>

                      End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.<br>
                      <button class="btn1 close" v-show="read5" @click="read5 = !read5"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br>
                    </p>
                  </div>
                </section>








                <section class="sec6">
                  <div v-show="!read6">
                    <h2 class="introHeader">When does check retail use customer information from third parties?</h2>
                    <button class="btn1 btn2 " v-show="!read6" @click="read6 = !read6"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read6">
                    <h2 class="subHeader">When does check retail use customer information from third parties?</h2><br><br>

                    <p>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a check retail customer, we receive information from a third party that provides automated fraud detection services to check retail. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
                    <button class="btn1 btn2 close" v-show="read6" @click="read6 = !read6"><p class="close-text">Close</p> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>






                <section class="sec7">
                  <div v-show="!read7">
                    <h2 class="introHeader">Do we share the information we collect with third parties?</h2>
                    <button class="btn1 btn3 " v-show="!read7" @click="read7 = !read7"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read7">
                    <h2 class="subHeader">Do we share the information we collect with third parties?</h2><br><br>

                    <p>
                      We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.<br><br>
                    </p>

                    <p v-show="showMore4">
                      We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.<br><br>

                      We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the app in a shared location, and type of the device used to visit the app. They may aggregate information about our advertising and what you see on the app and then provide auditing, research and reporting for us and our advertisers.<br><br>

                      We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
                    </p>
                    <button v-show="!showMore4" @click="showMore4 = !showMore4">Read More</button>
                    <button v-show="showMore4" @click="showMore4 = !showMore4">Show Less</button><br>
                    <button class="btn1 btn3 close" v-show="read7" @click="read7 = !read7"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br><br><br>
                  </div>
                </section>







                <section class="sec8">
                  <div v-show="!read8">
                    <h2 class="introHeader">Where and when is information collected from customers and end users?</h2>
                    <button class="btn1 btn4 " v-show="!read8" @click="read8 = !read8"><span class="close-text">Read</span><img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read8">
                    <h2 class="subHeader">Where and when is information collected from customers and end users? </h2><br>

                    <p>Check retail will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above</p>
                    <button class="btn1 btn4 close" v-show="read8" @click="read8 = !read8"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>

                <section class="sec9">
                  <div v-show="!read9">
                    <h2 class="introHeader">How Do We Protect Your Information?</h2>
                    <button class="btn1 " v-show="!read9" @click="read9 = !read9"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read9">
                    <h2 class="subHeader">How Do We Protect Your Information?</h2><br>

                    <p>
                      We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to check retail or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
                    </p>
                    <button class="btn1 close" v-show="read9" @click="read9 = !read9"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec10">
                  <div v-show="!read10">
                    <h2 class="introHeader">Could my information be transferred to other countries?</h2>
                    <button class="btn1 btn2" v-show="!read10" @click="read10 = !read10"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read10">
                    <h2 class="subHeader">Could my information be transferred to other countries?</h2><br>

                    <p>
                      Check retail is incorporated in Nigeria. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
                    </p>
                    <button class="btn1 btn2 close" v-show="read10" @click="read10 = !read10"><span class="close-text">Close</span><img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>





                <section class="sec11">
                  <div v-show="!read11">
                    <h2 class="introHeader">Is the information collected through the check retail Service secure?</h2>
                    <button class="btn1 btn3" v-show="!read11" @click="read11 = !read11"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read11">
                    <h2 class="subHeader">Is the information collected through the check retail Service secure?</h2><br>

                    <p>
                      We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
                    </p>
                    <button class="btn1 btn3 close" v-show="read11" @click="read11 = !read11"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>






                <section class="sec12">
                  <div v-show="!read12">
                    <h2 class="introHeader">Personnel</h2>
                    <button class="btn1 btn4" v-show="!read12" @click="read12 = !read12"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read12">
                    <h2 class="subHeader">Personnel</h2><br>

                    <p>
                      If you are a check retail worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.<br><br>

                      You may contact us in order to <br>(1) update or correct your information, <br>(2) change your preferences with respect to communications and other information you receive from us, or <br>(3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.
                    </p>
                    <button class="btn1 btn4 close" v-show="read12" @click="read12 = !read12"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>






                <section class="sec13">
                  <div v-show="!read13">
                    <h2 class="introHeader">Affiliates</h2>
                    <button class="btn1" v-show="!read13" @click="read13 = !read13"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read13">
                    <h2 class="subHeader">Affiliates</h2><br>

                    <p>
                      We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with check retail, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                    </p>
                    <button class="btn1 close" v-show="read13" @click="read13 = !read13"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec14">
                  <div v-show="!read14">
                    <h2 class="introHeader">Governing Law</h2>
                    <button class="btn1 btn2" v-show="!read14" @click="read14 = !read14"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read14">
                    <h2 class="subHeader">Governing Law</h2><br>

                    <p>
                      This Privacy Policy is governed by the laws of Nigeria without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.<br><br>

                      The laws of Nigeria, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. Your use of the app may also be subject to other local, state, national, or international laws.<br><br>

                      By using check retail or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
                    </p>
                    <button class="btn1 btn2 close" v-show="read14" @click="read14 = !read14"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>
                </section>





                <section class="sec15">
                  <div v-show="!read15">
                    <h2 class="introHeader">Your Consent</h2>
                    <button class="btn1 btn3" v-show="!read15" @click="read15 = !read15"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read15">
                    <h2 class="subHeader">Your Consent</h2><br>

                    <p>
                      We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our app, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
                    </p>
                    <button class="btn1 btn3 close" v-show="read15" @click="read15 = !read15"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>


                </section>





                <section class="sec16">
                  <div v-show="!read16">
                    <h2 class="introHeader">Payment Detail</h2>
                    <button class="btn1 btn4" v-show="!read16" @click="read16 = !read16"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read16">
                    <h2 class="subHeader">Payment Details</h2><br>

                    <p>
                      In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
                    </p>
                    <button class="btn1 btn4 close" v-show="read16" @click="read16 = !read16"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec17">
                  <div v-show="!read17">
                    <h2 class="introHeader">Kids' Privacy</h2>
                    <button class="btn1" v-show="!read17" @click="read17 = !read17"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read17">
                    <h2 class="subHeader">Kids' Privacy</h2><br>

                    <p>
                      We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                    </p>
                    <button class="btn1 close" v-show="read17" @click="read17 = !read17"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec18">
                  <div v-show="!read18">
                    <h2 class="introHeader">Changes To Our Privacy Policy</h2>
                    <button class="btn1 btn2" v-show="!read18" @click="read18 = !read18"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read18">
                    <h2 class="subHeader">Changes To Our Privacy Policy</h2><br>

                    <p>
                      We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
                    </p>
                    <button class="btn1 btn2 close" v-show="read18" @click="read18 = !read18"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec19">
                  <div v-show="!read19">
                    <h2 class="introHeader">Third-Party Services</h2>
                    <button class="btn1 btn3" v-show="!read19" @click="read19 = !read19"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read19">
                    <h2 class="subHeader">Third-Party Services</h2><br>

                    <p>
                      We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").
                      You acknowledge and agree that check retail shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. check retail does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.<br><br>

                      Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.<br>
                      <button class="btn1 btn3 close" v-show="read19" @click="read19 = !read19"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                    </p>

                  </div>

                </section>






                <section class="sec20">
                  <div v-show="!read20">
                    <h2 class="introHeader">Tracking Technologies</h2>
                    <button class="btn1 btn4" v-show="!read20" @click="read20 = !read20"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read20">
                    <h2 class="subHeader">Tracking Technologies</h2><br>

                    <p>
                      Google Maps API<br><br>
                      Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup just to name a few.<br><br>

                      Google Maps API may collect information from You and from Your Device for security purposes.<br><br>

                      Google Maps API collects information that is held in accordance with its Privacy Policy
                    </p>
                    <button class="btn1 btn4 close" v-show="read20" @click="read20 = !read20"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>





                <section class="sec21">
                  <div v-show="!read21">
                    <h2 class="introHeader">What is personal data</h2>
                    <button class="btn1" v-show="!read21" @click="read21 = !read21"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read21">
                    <h2 class="subHeader">What is personal data?</h2><br>

                    <p>
                      Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity
                    </p>
                    <button class="btn1 close" v-show="read21" @click="read21 = !read21"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






                <section class="sec22">
                  <div v-show="!read22">
                    <h2 class="introHeader">The Data Protection Principles include requirements such as:</h2>
                    <button class="btn1 btn2" v-show="!read22" @click="read22 = !read22"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read22">
                    <h2 class="subHeader">The Data Protection Principles include requirements such as:</h2><br>

                    <p>
                      <ul>
                        <li><p>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</p></li><br>
                        <li><p>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</p></li><br>
                        <li><p>Personal data should be held no longer than necessary to fulfil its purpose.</p></li><br>
                        <li><p>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</p></li>
                      </ul>
                    </p>
                    <button class="btn1 btn2 close" v-show="read22" @click="read22 = !read22"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>





                <section class="sec23">
                  <div v-show="!read23">
                    <h2 class="introHeader">Contact Us</h2>
                    <button class="btn1 btn3" v-show="!read23" @click="read23 = !read23"><span class="close-text">Read</span> <img src="../assets/images/Vector-caret.png" class="caret" ></button><br><br>
                  </div>

                  <div v-show="read23">
                    <h2 class="subHeader">Contact Us</h2><br>

                    <p>
                      Don't hesitate to contact us if you have any questions.<br><br>

                      <ul>
                        <li><p>Via Email:  hello.paddle@gmail.com</p></li>
                        <li><p>Via Phone Number:  08149734622</p></li>
                      </ul>
                    </p>
                    <button class="btn1 btn3 close" v-show="read23" @click="read23 = !read23"><span class="close-text">Close</span> <img src="../assets/images/Vector-caret-up.png" class="caret2" ></button><br><br><br>
                  </div>

                </section>






              </div>



            </div>
          </div>
          </div>
        </div>



        <!--<policyCom></policyCom>-->
        <footerLinks></footerLinks>
    </div>

</template>

<script>
import appHeader from '../components/headerNav.vue';
//import policyCom from '../components/policyComponent.vue';
import footerLinks from '../components/linksFooter.vue';

export default {
  name: 'privacyPolicy',
  components: {
    appHeader,
    //policyCom,
    footerLinks

  },
  data () {
    return {
      showMore1: false,
      showMore2: false,
      showMore3: false,
      showMore4: false,
      read1: false,
      read2: false,
      read3: false,
      read4: false,
      read5: false,
      read6: false,
      read7: false,
      read8: false,
      read9: false,
      read10: false,
      read11: false,
      read12: false,
      read13: false,
      read14: false,
      read15: false,
      read16: false,
      read17: false,
      read18: false,
      read19: false,
      read20: false,
      read21: false,
      read22: false,
      read23: false
    }
  }
}

</script>

<style scoped>

.policy {
  animation: fade-in 2s;
    /*background: rgb(255,240,252);
background: linear-gradient(87deg, rgba(255,240,252,0.9780287114845938) 35%, rgba(255,250,252,1) 73%);*/
}
.color {
    background-color: #FFF6FF;
    /* transform: translateY(-80px); */
    height: 350px;
    position: absolute;
    width: 100%;
}
.container-fluid {
  position: relative;
  /*border: 2px solid red;*/
  text-align: center;
  overflow-x: hidden;

}
.container {
  padding: 0px 46px 0px 46px;
}
.subheade-img {
  transform: translate(300px, -60px);
}

.introHeader {
  font-family: 'Euclid Circular A';
  font-style: normal;
  font-weight: 400;
  font-size: 40px;
  line-height: 50px;
  /* or 225% */

  display: flex;
  align-items: center;
  letter-spacing: -0.05em;

  color: #000000;

  display: inline-block;
  max-width: 600px;
}
.superHeader {
  color: black;

  font-family: 'Euclid Circular A';
  font-style: normal;
  font-weight: 600;
  font-size: 60px;
  line-height: 50px;

  text-align: center;
  letter-spacing: -0.05em;
  margin-top: 122px;
}
section {
  text-align: left;
  border-radius: 20px;
  padding: 40px 93px 23px 93px;
  margin-bottom: 40px;
}
section img {
  padding-left: 34px;
}

/*#sections section:nth-child(odd){
  background-color: #FFF3FF;
}
#sections section:nth-child(even){
  background-color: #EDF7FF;
}
#sections section:nth-child(3n){
  background-color: #E0FFED;
}
#sections section:nth-child(4n){
  background-color: #EBE7FF;
}*/

.sec1, .sec5 , .sec9, .sec13, .sec17, .sec21 {
  background-color: #FFF3FF;
}
.sec2, .sec6, .sec10, .sec14, .sec18, .sec22 {
  background-color: #EDF7FF;
}
.sec3, .sec7, .sec11, .sec15,.sec19, .sec23 {
  background-color: #E0FFED;
}
.sec4, .sec8, .sec12, .sec16, .sec20 {
  background-color: #EBE7FF;
}
.first-section {
  margin-top: 126px;
}
.subHeader {
  color: black;
  font-family: 'Euclid Circular A';
  font-style: normal;
  font-weight: 600;
  font-size: 50px;
  /*line-height: 90px;*/
  letter-spacing: 0.5;
}
p {
  color: black;
  font-family: 'Euclid Circular A';
  font-style: normal;
  font-weight: 300;
  font-size: 20px;
  line-height: 40px;
}
.mark-icon {
  margin-right: 5px;
}
table {
  margin-left: -4%;
}
/*table td {
  margin-left: 0%;
}*/
table td {
  vertical-align: top;
}

button {
  float: right;
  background: #40BC77;
  color: #fff;
  font-size: 30px;
  padding: 15px 40px;
  border: none;
  display: block;
  position: relative;
  display: inline-block;
}
button:hover {
  opacity: 0.8;
  transform: scale(1.02);
}
.btn1 {
  background: #F098A0;
  border-radius: 10px;
  padding-left: 25px;
  padding-right: 25px;
  padding-top: 10px;
  padding-bottom: 10px;
  display: inline-block;
  font-size: 25px;
}
.btn2 {
  background: #65BBFF;
}
.btn3 {
  background: #40BC77;
}
.btn4 {
  background: #AD9DFF
}
.close {
  /*transform: translateY(-50px);
  position: relative;
  margin-bottom: 240px;*/
  margin-top: 20px;
  /*margin-bottom: 320px;*/
  float: left;
}
.caret {
  padding: 0%;
  margin-left: 5px;
  animation-name: pointDown;
  animation-duration: 1s;
  animation-iteration-count: infinite;
}
.caret2 {
  padding: 0%;
  margin-left: 5px;
  animation-name: pointUp;
  animation-duration: 1s;
  animation-iteration-count: infinite;
}
section {
  transition: all 0.7s ease ;
}
/*.section3-table tr {
  border: 1px solid green;
  height: -5px;
  padding: 0%;
  margin: 0%;
}*/

@keyframes pointDown {
  0% {transform: translateY(5px);}
  25% {transform: translateY(1px);}
   50% {transform: translateY(0px);}
  75% {transform: translateY(1px);}
   100% {transform: translateY(5px);}
}
@keyframes pointUp {
  0% {transform: translateY(-5px);}
  25% {transform: translateY(-1px);}
   50% {transform: translateY(0px);}
  75% {transform: translateY(-1px);}
   100% {transform: translateY(-5px);}
}

@keyframes fade-in {
  from {
      opacity: 0;
      };
  to {
      opacity: 1;
  }
}


@media screen and (max-width: 800px) {
  .container {
    padding: 0px;
  }
  section {
    text-align: left;
    border-radius: 20px;
    padding: 20px;
    padding-bottom: 5px;/**where i made the section correction */
    margin-bottom: 10px;
  }
  section img {
    padding-left: 4px;
    height: 50px;
    width: 50px;
  }
  .introHeader {
    font-size: 24px;
    line-height: 40px;
    width:250px;
  }
  button {
    float: right;
    background: #40BC77;
    color: #fff;
    font-size: 16px;
    padding: 5px 20px;
    border: none;
  }
  table {
    margin-left: 0%;
  }
  .mark-icon {
    margin-right: 5px;
    height: 15px;
    width: 20px;
  }
  .btn1{
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 5px;
    padding-bottom: 5px;
    font-size: 25px;
  }
  /*.close {
    padding-top: 10px;
    padding-bottom: 10px;
  }*/
  .caret, .caret2 {
    height: 15px;
    width: 20px;
    margin-left: 0px;
  }

  .subheade-img {
    transform: translate(250px, -250px);
  }
  .close-text {
    display: none;
  }
  .close {
    margin-top: 20px;
    margin-bottom: 30px;
    float: left;
  }
  /*p {
    width: 310px;
  }*/
}

</style>